FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY gradlew /app/gradlew
COPY build.gradle settings.gradle /app/
COPY gradle /app/gradle

RUN chmod +x ./gradlew

RUN ./gradlew --no-daemon dependencies || true

EXPOSE 8761

CMD ["./gradlew", "bootRun", "--no-daemon"]
